/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EsRouteImport } from './routes/es'
import { Route as FrRouteImport } from './routes/fr'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as EsAboutRouteImport } from './routes/es_.about'
import { Route as EsPrivacyRouteImport } from './routes/es_.privacy'
import { Route as EsTermsRouteImport } from './routes/es_.terms'
import { Route as FrAboutRouteImport } from './routes/fr_.about'
import { Route as FrPrivacyRouteImport } from './routes/fr_.privacy'
import { Route as FrTermsRouteImport } from './routes/fr_.terms'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksPancakeRouteImport } from './routes/api/webhooks/pancake'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const EsAboutRoute = EsAboutRouteImport.update({
  id: '/es_/about',
  path: '/es/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EsPrivacyRoute = EsPrivacyRouteImport.update({
  id: '/es_/privacy',
  path: '/es/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EsTermsRoute = EsTermsRouteImport.update({
  id: '/es_/terms',
  path: '/es/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const FrAboutRoute = FrAboutRouteImport.update({
  id: '/fr_/about',
  path: '/fr/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FrPrivacyRoute = FrPrivacyRouteImport.update({
  id: '/fr_/privacy',
  path: '/fr/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FrTermsRoute = FrTermsRouteImport.update({
  id: '/fr_/terms',
  path: '/fr/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPancakeRoute = ApiWebhooksPancakeRouteImport.update({
  id: '/api/webhooks/pancake',
  path: '/api/webhooks/pancake',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/es/about': typeof EsAboutRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/terms': typeof EsTermsRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/terms': typeof FrTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/pancake': typeof ApiWebhooksPancakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/es/about': typeof EsAboutRoute
  '/es/privacy': typeof EsPrivacyRoute
  '/es/terms': typeof EsTermsRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/terms': typeof FrTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/pancake': typeof ApiWebhooksPancakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/es_/about': typeof EsAboutRoute
  '/es_/privacy': typeof EsPrivacyRoute
  '/es_/terms': typeof EsTermsRoute
  '/fr_/about': typeof FrAboutRoute
  '/fr_/privacy': typeof FrPrivacyRoute
  '/fr_/terms': typeof FrTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/pancake': typeof ApiWebhooksPancakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/es'
    | '/fr'
    | '/llms.txt'
    | '/login'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/es/about'
    | '/es/privacy'
    | '/es/terms'
    | '/fr/about'
    | '/fr/privacy'
    | '/fr/terms'
    | '/api/auth/$'
    | '/api/webhooks/pancake'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/es'
    | '/fr'
    | '/llms.txt'
    | '/login'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/es/about'
    | '/es/privacy'
    | '/es/terms'
    | '/fr/about'
    | '/fr/privacy'
    | '/fr/terms'
    | '/api/auth/$'
    | '/api/webhooks/pancake'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/es'
    | '/fr'
    | '/llms.txt'
    | '/login'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/es_/about'
    | '/es_/privacy'
    | '/es_/terms'
    | '/fr_/about'
    | '/fr_/privacy'
    | '/fr_/terms'
    | '/api/auth/$'
    | '/api/webhooks/pancake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  EsRoute: typeof EsRoute
  FrRoute: typeof FrRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  EsAboutRoute: typeof EsAboutRoute
  EsPrivacyRoute: typeof EsPrivacyRoute
  EsTermsRoute: typeof EsTermsRoute
  FrAboutRoute: typeof FrAboutRoute
  FrPrivacyRoute: typeof FrPrivacyRoute
  FrTermsRoute: typeof FrTermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksPancakeRoute: typeof ApiWebhooksPancakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es_/about': {
      id: '/es_/about'
      path: '/es/about'
      fullPath: '/es/about'
      preLoaderRoute: typeof EsAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es_/privacy': {
      id: '/es_/privacy'
      path: '/es/privacy'
      fullPath: '/es/privacy'
      preLoaderRoute: typeof EsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es_/terms': {
      id: '/es_/terms'
      path: '/es/terms'
      fullPath: '/es/terms'
      preLoaderRoute: typeof EsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr_/about': {
      id: '/fr_/about'
      path: '/fr/about'
      fullPath: '/fr/about'
      preLoaderRoute: typeof FrAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr_/privacy': {
      id: '/fr_/privacy'
      path: '/fr/privacy'
      fullPath: '/fr/privacy'
      preLoaderRoute: typeof FrPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr_/terms': {
      id: '/fr_/terms'
      path: '/fr/terms'
      fullPath: '/fr/terms'
      preLoaderRoute: typeof FrTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/pancake': {
      id: '/api/webhooks/pancake'
      path: '/api/webhooks/pancake'
      fullPath: '/api/webhooks/pancake'
      preLoaderRoute: typeof ApiWebhooksPancakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  EsRoute: EsRoute,
  FrRoute: FrRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  EsAboutRoute: EsAboutRoute,
  EsPrivacyRoute: EsPrivacyRoute,
  EsTermsRoute: EsTermsRoute,
  FrAboutRoute: FrAboutRoute,
  FrPrivacyRoute: FrPrivacyRoute,
  FrTermsRoute: FrTermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksPancakeRoute: ApiWebhooksPancakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
