/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EsRouteImport } from './routes/es'
import { Route as FrRouteImport } from './routes/fr'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksPancakeRouteImport } from './routes/api/webhooks/pancake'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPancakeRoute = ApiWebhooksPancakeRouteImport.update({
  id: '/api/webhooks/pancake',
  path: '/api/webhooks/pancake',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/pancake': typeof ApiWebhooksPancakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/pancake': typeof ApiWebhooksPancakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/es': typeof EsRoute
  '/fr': typeof FrRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/pancake': typeof ApiWebhooksPancakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/es'
    | '/fr'
    | '/llms.txt'
    | '/login'
    | '/manifest.webmanifest'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/auth/$'
    | '/api/webhooks/pancake'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/es'
    | '/fr'
    | '/llms.txt'
    | '/login'
    | '/manifest.webmanifest'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/auth/$'
    | '/api/webhooks/pancake'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/es'
    | '/fr'
    | '/llms.txt'
    | '/login'
    | '/manifest.webmanifest'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/auth/$'
    | '/api/webhooks/pancake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  EsRoute: typeof EsRoute
  FrRoute: typeof FrRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksPancakeRoute: typeof ApiWebhooksPancakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/pancake': {
      id: '/api/webhooks/pancake'
      path: '/api/webhooks/pancake'
      fullPath: '/api/webhooks/pancake'
      preLoaderRoute: typeof ApiWebhooksPancakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  EsRoute: EsRoute,
  FrRoute: FrRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksPancakeRoute: ApiWebhooksPancakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
